### PR TITLE
Updated parameters to support subgrouping_ids and grouped_time_entry_ids

### PR DESCRIPTION
**Pull request by MarkGrenville**
Update to support the new features: subgrouping_ids and grouped_time_entry_ids
https://github.com/toggl/toggl_api_docs/blob/master/reports/summary.md

### CODE REVIEW

**Comment by arendjantetteroo** [comment]
Cheers @MarkGrenville

**Comment by MarkGrenville** [comment]
Wow, I'm so happy you merged this so quickly... I'm still busy trying to figure out to use a git package with composer haha.

**Comment by arendjantetteroo** [comment]
I always appreciate the help and try to return the favor by merging quickly. especially if it's a small change like this one. I'll tag a new version so you can just update the composer package.

**Comment by MarkGrenville** [comment]
I did eventually manage to get composer to work with my fork so no major stress but I'll update back to your version as soon as it's available thanks again. Really helpful plugin

**Comment by arendjantetteroo** [comment]
i added v1.0.2 so you can upgrade to the default again.

**Pull request merged**
